[pytest]
addopts = -v  --html=reports/test_swaglabs.html
pythonpath = .
testpaths =
    tests
markers =
    smoke: critical test cases
    regression: full regression suite
    login: login related tests
    inventory: inventory tests
    cart: cart functionality tests