[pytest]
addopts = -v --html=reprosts/test_demo.html
pythonpath = .
testpaths =
    tests
markers =
    smoke: critical test cases
    regression: full regression suite
    login: login related tests
    inventory: inventory tests
    cart: cart functionality tests
    api: API test cases
    api_negative: negative test cases
    ui: UI cases